Default: &defaults
  database: auth-example.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: auth-example_test.sqlite3
  <<: *defaults

Staging:
  database: auth-example_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: auth-example_production.sqlite3
  poolsize: 100
  <<: *defaults
